### ISSUE TITLE
Modern language

### ISSUE THREAD

**Issue by nem0** [KelvinShadewing/XYG-Studio#14]
Did you consider writing the project in some modern language like Rust? And embedding something better, e.g. C#?

**Comment by Alan-FGR** [comment]
Rust sucks... just rewrite the whole shebang in C#

**Comment by Alan-FGR** [comment]
Depends on the scope of the engine, interop is slow so if the engine is minimalist and a lot of the logic happens in the scripts, it could very well be faster than a ton of pinvoke calls. Also, C# is not *that* slow.

**Comment by KelvinShadewing** [comment]
Guys, I'm not going to learn a new language just to rewrite this whole project from the ground up. C++ is very fast, as is Squirrel, which has already been used in the gaming industry by companies like Valve, Rockstar, and Sega. I already get little time as it is to code, which is partly why it's taken this long to get here, and I'm not starting over again.

**Comment by nem0** [comment]
Just because Squirrel was used by some gaming companies, does not mean it's good. Squirrel  will never have tools (IDE, debugger), docs, user base with such quality as C#

**Comment by Alan-FGR** [comment]
@nem0 you're a message thief, there's no honor in that man, here's the proof ([sauce](https://gitter.im/nem0/LumixEngine?at=5a04766986d308b755ca21d2)):
> lol, logical fallacy there: appeal to authority, just because companies use it doesn't mean it's good, and it's not: it sucks

I'm disappointed in you @nem0 :trollface:
